#!/bin/bash

sudo ufw reset
sudo ufw allow ssh
sudo ufw allow 8212
sudo ufw allow samba

sudo ufw default deny incoming
sudo ufw default deny outgoing
sudo ufw allow out on tun0 from any to any
sudo ufw enable