#!/bin/bash

echo "y" | sudo ufw reset

sudo ufw default deny incoming
sudo ufw default deny outgoing
allow
sudo ufw allow out on tun0 from any to any
sudo ufw allow in on tun0 from any to any

echo "y" |sudo ufw enable 